export const metadata = {
    title: "Posts Page",
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <>
            {children}
        </>
    )
}